language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

before_install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create --yes -q -n pyenv python=$TRAVIS_PYTHON_VERSION pillow numpy scipy nose pylint pip
  - source activate pyenv
  - pip install -e .

script:
 - pyssim test-images/test1-1.png test-images/test1-1.png | grep 1
 - pyssim test-images/test1-1.png test-images/test1-2.png | grep 0.998
 - pyssim test-images/test1-1.png "test-images/*" | grep -E " 1| 0.998| 0.672| 0.648" | wc -l | grep 4
 - pyssim --cw --width 128 --height 128 test-images/test1-1.png test-images/test1-1.png | grep 1
 - pyssim --cw --width 128 --height 128 test-images/test3-orig.jpg test-images/test3-rot.jpg | grep 0.938
 - pylint --rcfile=.pylintrc setup.py
 - pylint --rcfile=.pylintrc ssim
